### PR TITLE
Support surcharging

### PR DESCRIPTION
**Pull request by EricLin-BBpos**
## Summary

Add surcharging feature in  sdk

## Motivation

Support new surcharging feature

## Testing

- [ ] I tested this manually
- [x] I added automated tests

## Documentation

Select one:

- [ ] I have added relevant documentation for my changes.
- [x] This PR does not result in any developer-facing changes.

### CODE REVIEW

**Review by lins-stripe — COMMENTED** [review]
could you point me to where tests were added?

additionally, could you manually test with an account with the feature enabled, and a separate account without the feature enabled (to ensure errors are thrown if its not enabled)

**Comment by EricLin-BBpos** [comment]
> could you point me to where tests were added?
> 
> additionally, could you manually test with an account with the feature enabled, and a separate account without the feature enabled (to ensure errors are thrown if its not enabled)

Yep, we have manually tested both cases mentioned above.

**Comment by lins-stripe** [comment]
could you also add unit tests/automated tests if possible?

**Review by lins-stripe — APPROVED** [review]
ok i just talked with nazli, did not realize the RN repo is mainly just e2e/manual tests for now. lgtm then 👍

**Review by nazli-stripe — APPROVED** [review]

**Pull request merged**
